name: Auto Update Apps

on:
  schedule:
    - cron: '0 0 * * *' # 每天台灣時間早上 8 點自動執行
  workflow_dispatch: # 讓你可以手動點擊執行測試

jobs:
  run-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: pip install altparse

      - name: Execute Script
        run: python update_source.py

      - name: Save Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update apps.json"
          file_pattern: 'apps.json'
